version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: eduaguilar/reverseproxy
  backend-user:
    build:
      context: ../../udacity-c3-restapi-user
    image: eduaguilar/udacity-restapi-user
  backend-feed:
    build:
      context: ../../udacity-c3-restapi-feed
    image: eduaguilar/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend
    image: eduaguilar/udacity-frontend
